import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {

  console.log('testando')

  return (
    <div className={styles.container}>
      <Head>
        <title>To Do List App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          To Do List App
        </h1>
      </main>
    </div>
  )
}
